# Site settings
title: Christophe Estanol - Ruby on Rails and more...
description: Christophe Estanol is a Ruby on Rails developer based in Cali, Colombia
baseurl: ""
url: "http://chrisestanol.com"
image: img/logo.png
locale: en_US
author:
  name: Christophe Estanol
  email: hi@chrisestanol.com
  uri: https://twitter.com/chrisestanol
  facebook: christophe.estanol
  fb_id:
  twitter: chrisestanol
  github:  chrisestanol
  linkedin: chrisestanol

# Build settings
sass:
    sass_dir: _sass
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
permalink: pretty
paginate: 5

# Plugins
gems:      [jekyll-paginate]

# permalink: :categories/:title
