# Site settings
title: Christophe Estanol
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "chrisestanol.com"
url: "http://chrisestanol.com"
twitter_username: chrisestanol
github_username:  chrisestanol
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
