# Site settings
name: Christophe Estanol
description: Christophe Estanol's website
baseurl: ""
url: "http://chrisestanol.com"
author:
  name: Christophe Estanol
  email: hi@chrisestanol.com
  uri: https://twitter.com/chrisestanol
  twitter: chrisestanol
  github:  chrisestanol
  linkedin: chrisestanol

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# permalink: :categories/:title
