# Site settings
title: Christophe Estanol
email: your-email@yourdomain.com
description: "Christophe Estanol's website"
baseurl: ""
url: "http://chrisestanol.com"
twitter_username: chrisestanol
github_username:  chrisestanol
linkedin_username: chrisestanol

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Collections

collections:
  work:
    output: false
